spring:
  application:
    name: AnipingApp
  # ===============================
  # = DATASOURCE
  # ===============================
  datasource:
    # DB 연결 정보 (url, username, password는 실제 환경에 맞게 수정하세요)
    url: jdbc:mysql://localhost:3306/aniping?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  # ===============================
  # = JPA (Hibernate)
  # ===============================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
